import {
  Geist,
  Geist_Mono,
  Space_Grotesk,
  Inter,
  Meie_Script,
  Momo_Trust_Display,
  Lobster,
} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/UI/NavBar";
import Footer from "@/components/UI/Footer";

const logoFont = Lobster({
    variable: "--font-logo",
    weight: ["400"],
  subsets: ["latin"],
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-primary",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-secondary",
});

const meieScript = Meie_Script({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-fancy",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}) {
  return (
    <html lang="sk">
      <body
        className={[
          geistSans.variable,
          geistMono.variable,
          spaceGrotesk.variable,
          inter.variable,
          meieScript.variable,
          logoFont.variable,
          "antialiased bg-zinc-950",
        ].join(" ")}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
